# Generated by Django 5.1.6 on 2025-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beta', models.DecimalField(decimal_places=3, max_digits=5)),
                ('vol_avg', models.PositiveIntegerField()),
                ('mkt_cap', models.PositiveBigIntegerField()),
                ('last_div', models.DecimalField(decimal_places=2, max_digits=5)),
                ('range', models.CharField(max_length=64)),
                ('changes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=3)),
                ('cik', models.CharField(max_length=10)),
                ('isin', models.CharField(max_length=12)),
                ('cusip', models.CharField(max_length=9)),
                ('exchange', models.CharField(max_length=64)),
                ('exchange_short_name', models.CharField(max_length=16)),
                ('industry', models.CharField(max_length=128)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('ceo', models.CharField(max_length=128)),
                ('sector', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=3)),
                ('full_time_employees', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=8)),
                ('zip', models.CharField(max_length=16)),
                ('dcf_diff', models.DecimalField(decimal_places=5, max_digits=15)),
                ('dcf', models.DecimalField(decimal_places=14, max_digits=24)),
                ('image', models.URLField()),
                ('ipo_date', models.CharField(max_length=10)),
                ('default_image', models.BooleanField()),
                ('is_etf', models.BooleanField()),
                ('is_actively_trading', models.BooleanField()),
                ('is_adr', models.BooleanField()),
                ('is_fund', models.BooleanField()),
            ],
        ),
    ]
