# Generated by Django 5.1.6 on 2025-02-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpfin", "0002_companyprofile_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("symbol", models.CharField(max_length=5)),
                ("reported_currency", models.CharField(max_length=3)),
                ("cik", models.CharField(max_length=10)),
                ("filing_date", models.DateField()),
                ("accepted_date", models.DateTimeField()),
                ("calendar_year", models.CharField(max_length=4)),
                ("period", models.CharField(max_length=2)),
                ("revenue", models.BigIntegerField()),
                ("cost_of_revenue", models.BigIntegerField()),
                ("gross_profit", models.BigIntegerField()),
                (
                    "gross_profit_ratio",
                    models.DecimalField(decimal_places=10, max_digits=11),
                ),
                ("research_and_development_expenses", models.BigIntegerField()),
                ("general_and_administrative_expenses", models.BigIntegerField()),
                ("selling_and_marketing_expenses", models.BigIntegerField()),
                (
                    "selling_general_and_administrative_expenses",
                    models.BigIntegerField(),
                ),
                ("other_expenses", models.BigIntegerField()),
                ("operating_expenses", models.BigIntegerField()),
                ("cost_and_expenses", models.BigIntegerField()),
                ("interest_income", models.BigIntegerField()),
                ("interest_expense", models.BigIntegerField()),
                ("depreciation_and_amortization", models.BigIntegerField()),
                ("ebitda", models.BigIntegerField()),
                ("ebitda_ratio", models.DecimalField(decimal_places=10, max_digits=11)),
                ("operating_income", models.BigIntegerField()),
                (
                    "operating_income_ratio",
                    models.DecimalField(decimal_places=10, max_digits=11),
                ),
                ("total_other_income_expenses_net", models.BigIntegerField()),
                ("income_before_tax", models.BigIntegerField()),
                (
                    "income_before_tax_ratio",
                    models.DecimalField(decimal_places=10, max_digits=11),
                ),
                ("income_tax_expense", models.BigIntegerField()),
                ("net_income", models.BigIntegerField()),
                (
                    "net_income_ratio",
                    models.DecimalField(decimal_places=10, max_digits=11),
                ),
                ("eps", models.DecimalField(decimal_places=2, max_digits=5)),
                ("eps_diluted", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weighted_average_shs_out", models.BigIntegerField()),
                ("weighted_average_shs_out_dil", models.BigIntegerField()),
                ("link", models.URLField()),
                ("final_link", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="ipo_date",
            field=models.DateField(),
        ),
    ]
