# Generated by Django 5.1.6 on 2025-02-17 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corpfin", "0003_incomestatement_alter_companyprofile_ipo_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incomestatement",
            old_name="filing_date",
            new_name="filling_date",
        ),
    ]
