# Generated by Django 5.1.6 on 2025-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpfin", "0005_balancesheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesheet",
            name="inventory",
            field=models.BigIntegerField(null=True),
        ),
    ]
