# Generated by Django 5.1.6 on 2025-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpfin", "0006_alter_balancesheet_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesheet",
            name="goodwill",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="goodwill_and_intangible_assets",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="intangible_assets",
            field=models.BigIntegerField(null=True),
        ),
    ]
