# Generated by Django 5.1.6 on 2025-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "corpfin",
            "0008_alter_balancesheet_accumulated_other_comprehensive_income_loss_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesheet",
            name="final_link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="link",
            field=models.URLField(null=True),
        ),
    ]
